// GENERATED by scripts/gen-sounds.ts — do not edit by hand.
// Metro needs static require() literals, so the map is emitted rather than built at runtime.

export const SOUND_SAMPLE_RATE = 22050;
export const SOUND_MIDI_LOW = 40;
export const SOUND_MIDI_HIGH = 79;

/** MIDI number -> bundled WAV module. */
export const SAMPLES: Record<number, number> = {
  40: require('../../assets/sounds/40.wav'),
  41: require('../../assets/sounds/41.wav'),
  42: require('../../assets/sounds/42.wav'),
  43: require('../../assets/sounds/43.wav'),
  44: require('../../assets/sounds/44.wav'),
  45: require('../../assets/sounds/45.wav'),
  46: require('../../assets/sounds/46.wav'),
  47: require('../../assets/sounds/47.wav'),
  48: require('../../assets/sounds/48.wav'),
  49: require('../../assets/sounds/49.wav'),
  50: require('../../assets/sounds/50.wav'),
  51: require('../../assets/sounds/51.wav'),
  52: require('../../assets/sounds/52.wav'),
  53: require('../../assets/sounds/53.wav'),
  54: require('../../assets/sounds/54.wav'),
  55: require('../../assets/sounds/55.wav'),
  56: require('../../assets/sounds/56.wav'),
  57: require('../../assets/sounds/57.wav'),
  58: require('../../assets/sounds/58.wav'),
  59: require('../../assets/sounds/59.wav'),
  60: require('../../assets/sounds/60.wav'),
  61: require('../../assets/sounds/61.wav'),
  62: require('../../assets/sounds/62.wav'),
  63: require('../../assets/sounds/63.wav'),
  64: require('../../assets/sounds/64.wav'),
  65: require('../../assets/sounds/65.wav'),
  66: require('../../assets/sounds/66.wav'),
  67: require('../../assets/sounds/67.wav'),
  68: require('../../assets/sounds/68.wav'),
  69: require('../../assets/sounds/69.wav'),
  70: require('../../assets/sounds/70.wav'),
  71: require('../../assets/sounds/71.wav'),
  72: require('../../assets/sounds/72.wav'),
  73: require('../../assets/sounds/73.wav'),
  74: require('../../assets/sounds/74.wav'),
  75: require('../../assets/sounds/75.wav'),
  76: require('../../assets/sounds/76.wav'),
  77: require('../../assets/sounds/77.wav'),
  78: require('../../assets/sounds/78.wav'),
  79: require('../../assets/sounds/79.wav'),
};

export const hasSample = (midi: number) => midi in SAMPLES;
